### ISSUE TITLE
Upgrade to emotion 9

### ISSUE THREAD

**Issue by ayc92** [kamiyo/sycpiano#108]
Here's the changelog: https://github.com/emotion-js/emotion/blob/master/CHANGELOG.md

**Comment by kamiyo** [comment]
Shouldn't cause too much of a trouble. Let's finish porting less over though. I've almost finished it, I just haven't pushed it on.

**Comment by ayc92** [comment]
Yeah, we can do this later, maybe after the first website release.

**Comment by kamiyo** [comment]
done with commit 31eed4a259f0168e5b358ef32498fa413b4d1edf
