### ISSUE TITLE
Don't use thumbnails for mobile photos page

### ISSUE THREAD

**Issue by ayc92** [kamiyo/sycpiano#141]
Currently, the photos page on mobile just sets the playlist width to 100%, which means it'll be using the thumbnails. Discussion was initially brought up here: https://github.com/kamiyo/sycpiano/issues/124#issuecomment-367921758

We should instead choose one of these three approaches:

- Have the thumbnails actually link to the asset urls when the user clicks/taps it
- Build a lightbox for displaying the actual full photo when the user clicks/taps it
- Somehow just show the full image instead of the thumbnails when on a mobile device

**Comment by kamiyo** [comment]
fixed in #149
