### ISSUE TITLE
Show event details on the left side

### ISSUE THREAD

**Issue by ayc92** [kamiyo/sycpiano#25]
Instead of showing the calendar, let's show the event details.

## Details Spec
- repertoire
- collaborators
- map
- link to external site

NOTE: by default, display closest upcoming event

**Comment by kamiyo** [comment]
After talking with daddy:

add day of week to list
also maybe add ability to share stuff via twitter/fb etc.

**Comment by ayc92** [comment]
Both sounds like good ideas. I won't address them in this issue's PR though. I'll go ahead and add them as separate issues.
