### ISSUE TITLE
Add share buttons and permalink for each list item

### ISSUE THREAD

**Issue by ayc92** [kamiyo/sycpiano#27]
Up to the implementer to decide what icons to use.

We already have some sharing-related components used by the contacts page, so maybe we can pull those out into a shared directory and re-use them.

**Comment by kamiyo** [comment]
Permalink is implemented for music and schedule.

Videos and photos don't have that currently, but might not be necessary.

**Comment by ayc92** [comment]
Closing this issue. I don't think list items need permalinks.
