### ISSUE TITLE
Beautify event list details sidebar

### ISSUE THREAD

**Issue by ayc92** [kamiyo/sycpiano#34]
This is follow-up work for https://github.com/kamiyo/sycpiano/issues/29

**Comment by ayc92** [comment]
@kamiyo @jschen5 how about something like this for event details?

![img_20170922_230816](https://user-images.githubusercontent.com/1166548/30770683-513f90a6-9feb-11e7-8182-22c92effb6bf.jpg)

I didn't put a map under "location", but we could. Or we could make clicking on it bring you to the corresponding google maps page.

Clicking on "program" would show program info, and "featuring" would should any collaborators (if it's just @kamiyo, I guess we can just say "this is a solo concert" or something).

Pros:
- Less cluttered
- Don't have to worry about not having enough space to fit info

Cons:
- More clicks to get to info
- Some info hidden unless user clicks the respective tab

**Comment by kamiyo** [comment]
I like the icon  and minimal idea... can we just fit it all on one page though? The text and icons don't have to be so big. I do think the cons are big with the tabs.

**Comment by ayc92** [comment]
I think we can fit it all on one page if we're not going to have that much info for "featuring" or "program".

The reason I originally put it on separate tabs was because I was thinking that for...
"featuring" we could add a bio/details/image for each featured artist/orchestra
"program" we could put a bio/image for each composer

I don't think the bio/images in "program" are that useful, but I kind of like the idea of the "featuring" counterparts.

**Comment by kamiyo** [comment]
I don't think we need bio/images for everything, mostly because if we link to their website, that stuff is all on there.

They usually also have like themes of the concert and stuff, so I think we should leave that up to the presenters. My 2c

**Comment by kamiyo** [comment]
One image is probably fine. If we can use opengraph and get whatever the website is putting as the og:image then I think that's good enough?

**Comment by ayc92** [comment]
That sounds good to me. I'll see if I can get another (jank) design up.

**Comment by kamiyo** [comment]
arigato!

**Comment by ayc92** [comment]
A first attempt at making it look okay: https://github.com/kamiyo/sycpiano/issues/62

**Comment by jschen5** [comment]
New issue for final design: https://github.com/kamiyo/sycpiano/issues/74
