### ISSUE TITLE
Is animating event list scroll necessary?

### ISSUE THREAD

**Issue by kamiyo** [kamiyo/sycpiano#37]
That, and google maps loading makes the scrolling stutter. If we do keep it, we need to probably either scroll first, then fetch google map, or scroll after

**Comment by ayc92** [comment]
Hmmm, maybe we can load gmaps (i.e. mount the map component) after the scrolling animation is finished. This'll just require adding an extra state variable in our redux store.

**Comment by kamiyo** [comment]
yea i thought about that. I'll try to do it in my animation branch.
