### ISSUE TITLE
webpack not rebundling on stylesheet changes

### ISSUE THREAD

**Issue by kamiyo** [kamiyo/sycpiano#38]

**Comment by ayc92** [comment]
@kamiyo it does for me...

**Comment by kamiyo** [comment]
hrm....  i'm on master, and it's not rebundling after I save a less file.

**Comment by kamiyo** [comment]
it's on my laptop, so i dunno if there's something wrong, but i'll try at home and see if it still doesn't work

**Comment by kamiyo** [comment]
yea it's not doing it for me on the laptop. I have to kill npm and then restart it for the changes to take effect
