### ISSUE TITLE
Modify collaborator schema to include name, instrument/role

### ISSUE THREAD

**Issue by ayc92** [kamiyo/sycpiano#44]
I noticed that for event details, it'll be cleaner to have a collaborator look like:

```
{ name: 'Bob Bobbers', instrument: 'trumpet' }
```

instead of enforcing that a collaborator is a CSV (e.g. `'Bob Bobbers, trumpet'`).

We'll need to update event forms in admin page to either parse a CSV input, or to split the `collaborators` input into 2 inputs

**Comment by ayc92** [comment]
On second thought, I'm actually okay with enforcing CSV format per collaborator entry. In that case, I'll just close this issue.

**Comment by kamiyo** [comment]
We can modify the model to support this if it's still desired.

**Comment by kamiyo** [comment]
CSV splitting implemented in seeder
