### ISSUE TITLE
Extract styles into stylesheet for prod

### ISSUE THREAD

**Issue by kamiyo** [kamiyo/sycpiano#89]
https://github.com/webpack-contrib/extract-text-webpack-plugin

**Comment by ayc92** [comment]
I think we actually want to use this: https://github.com/4Catalyzer/css-literal-loader

The `extract-text-webpack-plugin` is used for css modules, not css-in-js.

**Comment by kamiyo** [comment]
We can't use extract text if we want dynamic interpolation. see https://github.com/emotion-js/emotion/blob/master/docs/extract-static.md
